[package]
name = "rust-grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
yellowstone-grpc-client = "6.0.0"
tonic = { version = "0.10", features = ["tls"] }
dotenvy = "0.15"